/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative */

#ifndef _Included_cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative
#define _Included_cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative_hello
  (JNIEnv *, jclass);

/*
 * Class:     cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative
 * Method:    httpRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative_httpRequest (
    JNIEnv * env,
    jclass class,
    jstring method,
    jstring protocol,
    jstring path,
    jstring host,
    jstring user_agent,
    jstring authorization,
    jstring content
    );

#ifdef __cplusplus
}
#endif
#endif
