/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "../../../../../../java/jdk1.8.0_40/include/jni.h"
/* Header for class cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative */

#ifndef _Included_cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative
#define _Included_cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative
 * Method:    httpRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative_httpRequest
  (JNIEnv * env, jclass obj, jstring a, jstring b, jstring c, jstring d, jstring e, jstring f, jstring g, jstring h);

//std::string HttpNative_httpRequest(const char* method, const char* protocol, const char* jpath, const char* host, const char* userAgent, const char* authorization, const char* content);

#ifdef __cplusplus
}
#endif
#endif
