/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative */

#ifndef _Included_cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative
#define _Included_cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cz_muni_fi_ib053_twitter_client_twitterapi_HttpNative_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
